"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var cors_1 = require("cors");
var cookie_parser_1 = require("cookie-parser");
var path_1 = require("path");
var env_js_1 = require("./config/env.js");
var auth_routes_js_1 = require("./routes/auth.routes.js");
var course_routes_js_1 = require("./routes/course.routes.js");
var announcement_routes_js_1 = require("./routes/announcement.routes.js");
var material_routes_js_1 = require("./routes/material.routes.js");
var app = (0, express_1.default)();
app.use((0, cors_1.default)({ origin: env_js_1.env.CLIENT_ORIGIN || "http://localhost:5173", credentials: true }));
app.use(express_1.default.json());
app.use((0, cookie_parser_1.default)());
app.use("/static", express_1.default.static(path_1.default.join(process.cwd(), "src", "uploads")));
app.get("/api/health", function (_req, res) { return res.json({ ok: true }); });
app.get("/", function (_req, res) { return res.send("API radi!"); });
app.use("/api/auth", auth_routes_js_1.default);
app.use("/api/courses", course_routes_js_1.default);
app.use("/api/announcements", announcement_routes_js_1.default);
app.use("/api/materials", material_routes_js_1.default);
exports.default = app;
